### PR TITLE
SkBee - 1.17.x

### PR DESCRIPTION
**Pull request by ShaneBeee**
This PR is a focus on a future version of SkBee with some new features.

Features so far added:
- Statistics #179 
- Villager elements (level, experience, profession, type) #180
- Merchant elements (merchants, merchant recipes, trade select event) #180 
- Update particle effect to include `force` #183 
- New `/skbee info` command (used for debugging purposes)
- New update checker (will print in console if an update is available)
- Expression for getting ticks/seconds/minutes/hours from a timespan #195 
- Potion change event
- Show demo screen effect #195 
- Effect to load/unload a chunk (with optional ticket) #195 
- Breed event, event values, expression for breed event entities (parents, baby, breeder) #195 
- Advancement objects, event, expressions #195 
- WorldBorder elements (including virtual world borders for players) #195 
- Expression to get/set spell of a spell caster #142

### CODE REVIEW

**Comment by J-ak-e** [comment]
add the glowing/shiny expression for items

**Comment by J-ak-e** [comment]
add some kind of citizen/nps system OR a way to add fake players to tab with the option to make them only visible to a single player (basically adds a way to make hypixel skyblock-like tablists!)

**Comment by ShaneBeee** [comment]
> add the glowing/shiny expression for items

I personally don't think this is needed. You can already do this with SkBee, by enchanting an item and hiding the enchants flag. (ps, that is literally what SkQuery's expression does already).
This is what I meant up top by "lazy syntax", this isn't a "Minecraft thing", its just a lazy shortcut to doing what can already be done with Skript.

> add some kind of citizen/nps system OR a way to add fake players to tab with the option to make them only visible to a single player (basically adds a way to make hypixel skyblock-like tablists!)

This would require an external API, which as I said above, I won't be doing.

**Comment by GeoGb1** [comment]
I see that you have added the item cooldown syntax and i tried to use it to make a sword cancel the shield (like the axe does by deafult), but it doesnt work.

**Comment by ShaneBeee** [comment]
> I see that you have added the item cooldown syntax and i tried to use it to make a sword cancel the shield (like the axe does by deafult), but it doesnt work.
> (sorry if this is not the right place to add this comment)

a) no, commenting on a closed PR is most definitely not the place to be commenting
b) my guess is the effect isn't working how you expect it. I've tested it plenty of times, it 100% works. Check the docs for it, the effect doesn't block things like sword usage (that's just how MC works)

**Pull request merged**
