### PR TITLE
Change Rotation ClassInfo name

### PR DESCRIPTION
**Pull request by TheLimeGlass**
Changing ClassInfo name of StructureRotation to "structurerotation"

Causes conflicts with other addons and I believe name `rotation` should be reserved for `org.bukkit.rotation`

Also adds gitignores.

### CODE REVIEW

**Comment by ShaneBeee** [comment]
This would also need to be changed in the elements/syntaxes that use this classinfo

**Comment by TheLimeGlass** [comment]
I didn't see a usage in a syntax

**Comment by ShaneBeee** [comment]
Oh you're right my bad, its not actually used in the expression as a classinfo

**Review by ShaneBeee — APPROVED** [review]
Looks good to me

**Pull request merged**
